#index:
#    path: /
#    controller: App\Controller\DefaultController

accueil:
    path: /
    controller: App\Controller\AccueilController::index


visiteur:
    path: /visiteur
    controller: App\Controller\VisiteurController::index
    
    
menuv:
    path: /visiteur/menu
    controller: App\Controller\MenuVController::index

    
consulter:
    path: /visiteur/consulter
    controller: App\Controller\ConsulterController::index

renseigner:
    path: /visiteur/renseigner
    controller: App\Controller\RenseignerController::index
    
renseignerff:
    path: /visiteur/renseignerff
    controller: App\Controller\RenseignerffController::index

renseignerhf:
    path: /visiteur/renseignerhf
    controller: App\Controller\RenseignerhfController::index    
    
#menu:
#    path: /visiteur/menu
#    controller: App\Controller\MenuVController::index
